[build]
command = 'bun run build'
publish = 'dist'

[[headers]]
for = '/*'
[headers.values]
access-control-allow-origin = '*'
referrer-policy = 'same-origin'
x-content-type-options = 'nosniff'
x-frame-options = 'sameorigin'

[[headers]]
for = '/manifest.webmanifest'
[headers.values]
content-type = 'application/manifest+json'
